version: '3'
services:
  mysql:
    build: ./
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
    container_name: mysql
    user: "1000:1000"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
